import { Burger } from "./Burger.model";

export const BURGERS: Burger[] = [
  { id: 1,
  quantity: 0,
  price: 8.50,
  name: "Cocktail Burger",
  ingredients: ["pain", "salade", "sauce cocktail"],
  isAvailable: true,
  url: "./assets/cocktail-burger.jpg"},
  { id: 2,
  quantity: 0,
  price: 7.50,
  name: "Bacon Burger",
  ingredients: ["pain", "salade", "bacon"],
  isAvailable: false,
  url: "./assets/bacon-burger.jpg"},
  { id: 3,
  quantity: 0,
  price: 5.50,
  name: "Dream Burger",
  ingredients: ["pain", "salade", "bacon"],
  isAvailable: true,
  url: "./assets/dream-burger.jpg"},
  { id: 4,
    quantity: 0,
    price: 7.50,
    name: "Double Burger",
    ingredients: ["pain", "salade", "bacon"],
    isAvailable: true,
    url: "./assets/double-burger.jpg"},
];
